name: Waka Readme

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  schedule:
    - cron:  '0 10,20 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          LANG_COUNT: 8
          SHOW_TOTAL: true
